### ISSUE TITLE
failure to call phylok2 from command line

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/latency-model#1]
Importing issue from PoonLab/PoonLab#15

**Comment by ArtPoon** [comment]
@mavino, please provide details on your attempts to run the script and the output messages you receive

**Comment by mavino** [comment]
the command I run:
python phyloK2.py -f Coevolution/Total.nwk > Coevolution/Results
no output message on command line
the output file is blank
if I remove the option -f I will have the same result

**Comment by ArtPoon** [comment]
Okay, now that I've looked at the file it's coming back to me now.  `phyloK2.py` was never meant to be called from the command line.  In particular, it doesn't have the following lines:
```
if __name__ == '__main__':
    main()
```
that would enable one to call it from the command line. 
`phyloK2.py` was meant to be loaded as a module that provides a class, called `PhyloKernel`.  This class contains the methods used to calculate the tree kernel.

Since this is not intuitive (after all, I completely forgot about this), I am going to refactor this script.

**Comment by mavino** [comment]
Hi Art,
could you tell me again which of the scripts in the latency-model folder src I have to utilize in order to compare the trees? Was it prepareKernel.py or run-kernel.py? Thanks

**Comment by ArtPoon** [comment]
run-kernel.py
